version: "3"

services:
#  mavros:
#    container_name: px4_ros
#    build:
#      context: mavros
#      dockerfile: Dockerfile
##    ports:
##    - "11311:11311"
#    volumes:
#    - "../:/home/user/AutoDock:ro" # Mount the repo in the user's home dir
#    - "./scripts/:/home/user/scripts"

  simulator:
    container_name: px4_sim
    build:
      context: simulator-nvidia
      dockerfile: Dockerfile
    privileged: true
    environment:
      DISPLAY: ":0"
    ports:
    - "14556:14556/udp"
    - "5600:5600/udp"
    volumes:
    - "../:/root/AutoDock"
    - "/tmp/.X11-unix:/tmp/.X11-unix:ro"